package:  quicklinks
version:  '2.2'
author:   Wolfgang Busch
supportpage: redaxo.org/forum/

page:
    title: 'translate:quicklinks'
    perm:  admin[]
    icon:  rex-icon fa-reorder
    subpages:
        introduction: { title: 'translate:introduction' }
        description:  { title: 'translate:description' }
        example:      { title: 'translate:example' }
        settings:     { title: 'translate:settings' }

requires:
    redaxo: ^5.3.0
