package: quicklinks
version: '2.0.0'
author: 'Wolfgang Busch'
supportpage: redaxo.org/forum/

page:
    title: 'translate:quicklinks'
    perm: quicklinks[]
    subpages:
        introduction: { title: 'translate:introduction' }
        description:  { title: 'translate:description' }
        example:      { title: 'translate:example' }
        settings:     { title: 'translate:settings' }

requires:
    redaxo: ^5.3.0
